packages:
  - "apps/*"
  - "packages/*"
  - "tests/e2e"

allowBuilds:
  argon2: true
  esbuild: true
  workerd: true

enableGlobalVirtualStore: false
managePackageManagerVersions: false
confirmModulesPurge: false
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@oxc-project/types"
  - "@rolldown/*"
  - "electron-to-chromium"
  - "rolldown"
