export type FinancialInvariantIssue =
  | "ACCOUNT_BALANCE_NEGATIVE"
  | "ACCOUNT_BALANCE_OVERFLOW"
  | "ACCOUNT_DEFINITION_MISMATCH"
  | "ACCOUNT_OPENING_BALANCE_DENOMINATION_MISMATCH"
  | "DEPOSIT_AMOUNT_NOT_POSITIVE"
  | "DEPOSIT_CREDITED_AT_INVALID"
  | "DEPOSIT_DENOMINATION_MISMATCH"
  | "DEPOSIT_JOURNAL_ID_INVALID"
  | "JOURNAL_ASSET_SCALE_MISMATCH"
  | "JOURNAL_POSITION_SEQUENCE_INVALID"
  | "JOURNAL_TOO_FEW_POSTINGS"
  | "JOURNAL_UNBALANCED"
  | "POSTING_AMOUNT_NOT_POSITIVE"
  | "POSTING_DENOMINATION_MISMATCH"
  | "POSTING_POSITION_INVALID"
  | "WALLET_ACCOUNT_IDS_NOT_DISTINCT"
  | "WALLET_BALANCE_DENOMINATION_MISMATCH"
  | "WALLET_BALANCE_OVERFLOW"
  | "TRADING_FUNDS_PLAN_INVALID"
  | "TRADING_RELEASE_CONFLICT"
  | "TRADING_RESERVATION_CONFLICT"
  | "TRADING_RESERVATION_NOT_FOUND"
  | "TRADING_SETTLEMENT_CONFLICT"
  | "WITHDRAWAL_AMOUNT_NOT_POSITIVE"
  | "WITHDRAWAL_COMPLETED_AT_INVALID"
  | "WITHDRAWAL_DENOMINATION_MISMATCH"
  | "WITHDRAWAL_JOURNAL_ID_INVALID";

export class FinancialInvariantError extends Error {
  public constructor(public readonly issue: FinancialInvariantIssue) {
    super(`Financial invariant violated: ${issue}.`);
    this.name = "FinancialInvariantError";
  }
}
